# Generated by Django 6.0 on 2026-01-02 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='Store_custo_phone_n_13e5f0_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Store_customer',
        ),
    ]
